# Generated by Django 5.0.6 on 2025-04-24 06:28

import authentication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rol",
            options={"verbose_name": "Rol", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", authentication.models.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name="rol",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rol",
            name="nombre",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("VETERINARIO", "Veterinario"),
                    ("RECEPCIONISTA", "Recepcionista"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.ForeignKey(
                db_column="rol_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="authentication.rol",
            ),
        ),
    ]
