# Generated by Django 5.0.6 on 2025-05-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Especie",
                "verbose_name_plural": "Especies",
            },
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("H", "Hembra")], max_length=1
                    ),
                ),
                ("esterilizado", models.BooleanField(default=False)),
                (
                    "microchip",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mascotas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mascotas",
                        to="mascotas.especie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mascota",
                "verbose_name_plural": "Mascotas",
            },
        ),
        migrations.CreateModel(
            name="FotoMascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url_foto", models.ImageField(upload_to="mascotas/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="mascotas.mascota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de Mascota",
                "verbose_name_plural": "Fotos de Mascotas",
            },
        ),
        migrations.CreateModel(
            name="Raza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="razas",
                        to="mascotas.especie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raza",
                "verbose_name_plural": "Razas",
                "unique_together": {("nombre", "especie")},
            },
        ),
        migrations.AddField(
            model_name="mascota",
            name="raza",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mascotas",
                to="mascotas.raza",
            ),
        ),
        migrations.CreateModel(
            name="RegistroPeso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_registro", models.DateField()),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_peso",
                        to="mascotas.mascota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Peso",
                "verbose_name_plural": "Registros de Peso",
            },
        ),
    ]
