# Generated by Django 5.0.6 on 2025-05-14 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("mascotas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "duracion_estimada",
                    models.IntegerField(help_text="Duración en minutos"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Consulta",
                "verbose_name_plural": "Tipos de Consulta",
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
            },
        ),
        migrations.CreateModel(
            name="HistorialMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "mascota",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="mascotas.mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historiales_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial Médico",
                "verbose_name_plural": "Historiales Médicos",
            },
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ACTIVA",
                        max_length=20,
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas",
                        to="mascotas.mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas_emitidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta",
                "verbose_name_plural": "Recetas",
            },
        ),
        migrations.CreateModel(
            name="DetalleReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dosis", models.CharField(max_length=100)),
                ("frecuencia", models.CharField(max_length=100)),
                ("duracion", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField()),
                ("instrucciones", models.TextField()),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas",
                        to="inventario.medicamento",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="historial_medico.receta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Receta",
                "verbose_name_plural": "Detalles de Recetas",
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField()),
                ("motivo_consulta", models.TextField()),
                ("diagnostico", models.TextField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "historial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="historial_medico.historialmedico",
                    ),
                ),
                (
                    "tipo_consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="historial_medico.tipoconsulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("url_archivo", models.FileField(upload_to="documentos/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="mascotas.mascota",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_subidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "historial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="historial_medico.historialmedico",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="historial_medico.tipodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
            },
        ),
        migrations.CreateModel(
            name="Tratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descripcion", models.TextField()),
                ("duracion", models.CharField(max_length=100)),
                ("inicio_tratamiento", models.DateField()),
                ("fin_tratamiento", models.DateField(blank=True, null=True)),
                ("instrucciones", models.TextField()),
                (
                    "historial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tratamientos",
                        to="historial_medico.historialmedico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratamiento",
                "verbose_name_plural": "Tratamientos",
            },
        ),
        migrations.CreateModel(
            name="Vacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("OBLIGATORIA", "Obligatoria"),
                            ("OPCIONAL", "Opcional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "intervalo_revacunacion",
                    models.PositiveIntegerField(help_text="Intervalo en días"),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacunas",
                        to="mascotas.especie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacuna",
                "verbose_name_plural": "Vacunas",
            },
        ),
        migrations.CreateModel(
            name="MascotaVacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_aplicacion", models.DateField()),
                ("fecha_proxima", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacunaciones",
                        to="inventario.lotemedicamento",
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacunaciones",
                        to="mascotas.mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacunaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aplicaciones",
                        to="historial_medico.vacuna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacuna Aplicada",
                "verbose_name_plural": "Vacunas Aplicadas",
            },
        ),
    ]
