# Generated by Django 5.0.6 on 2025-05-14 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("historial_medico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="cita_relacionada",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID de la cita original en el módulo de citas",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso en kilogramos",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="sintomas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="temperatura",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Temperatura en grados Celsius",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="tratamiento",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="consulta",
            constraint=models.UniqueConstraint(
                fields=("historial", "fecha", "cita_relacionada"),
                name="unique_consulta_per_cita",
            ),
        ),
    ]
