# Generated by Django 5.0.6 on 2025-05-10 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("historial_medico", "0001_initial"),
        ("inventario", "0001_initial"),
        ("mascotas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ACTIVA",
                        max_length=20,
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas",
                        to="mascotas.mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas_emitidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta",
                "verbose_name_plural": "Recetas",
            },
        ),
        migrations.CreateModel(
            name="DetalleReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dosis", models.CharField(max_length=100)),
                ("frecuencia", models.CharField(max_length=100)),
                ("duracion", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField()),
                ("instrucciones", models.TextField()),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas",
                        to="inventario.medicamento",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="historial_medico.receta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Receta",
                "verbose_name_plural": "Detalles de Recetas",
            },
        ),
        migrations.CreateModel(
            name="Vacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("OBLIGATORIA", "Obligatoria"),
                            ("OPCIONAL", "Opcional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "intervalo_revacunacion",
                    models.PositiveIntegerField(help_text="Intervalo en días"),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacunas",
                        to="mascotas.especie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacuna",
                "verbose_name_plural": "Vacunas",
            },
        ),
        migrations.CreateModel(
            name="MascotaVacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_aplicacion", models.DateField()),
                ("fecha_proxima", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacunaciones",
                        to="inventario.lotemedicamento",
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacunaciones",
                        to="mascotas.mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacunaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aplicaciones",
                        to="historial_medico.vacuna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacuna Aplicada",
                "verbose_name_plural": "Vacunas Aplicadas",
            },
        ),
    ]
