# Generated by Django 5.0.6 on 2025-04-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "indexes": [
                    models.Index(fields=["rut"], name="clientes_cl_rut_43a54a_idx"),
                    models.Index(fields=["email"], name="clientes_cl_email_eae461_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DireccionCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("calle", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=20)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ciudad", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direcciones",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección de Cliente",
                "verbose_name_plural": "Direcciones de Clientes",
            },
        ),
    ]
