# Generated by Django 5.0.6 on 2025-05-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="direccioncliente",
            name="comuna",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="rut",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
