# Generated by Django 5.0.6 on 2025-05-19 22:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_direccioncliente_comuna_alter_cliente_rut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="direccioncliente",
            name="comuna",
        ),
    ]
