# Generated by Django 5.0.6 on 2025-05-10 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ORAL", "Oral"),
                            ("INYECTABLE", "Inyectable"),
                            ("TOPICO", "Tópico"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("presentacion", models.CharField(max_length=100)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_minimo", models.PositiveIntegerField()),
                ("activo", models.BooleanField(default=True)),
                ("requiere_receta", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
            },
        ),
        migrations.CreateModel(
            name="LoteMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero_lote", models.CharField(max_length=50)),
                ("fecha_vencimiento", models.DateField()),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha_ingreso", models.DateField()),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="inventario.medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Medicamento",
                "verbose_name_plural": "Lotes de Medicamentos",
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateTimeField()),
                (
                    "documento_referencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("motivo", models.TextField()),
                ("afecta_stock", models.BooleanField(default=True)),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventario.lotemedicamento",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventario.medicamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MEDICAMENTOS", "Medicamentos"),
                            ("ALIMENTOS", "Alimentos"),
                            ("EQUIPOS", "Equipos"),
                            ("SERVICIOS", "Servicios"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="inventario__nombre_70461d_idx"
                    ),
                    models.Index(fields=["email"], name="inventario__email_3b67b1_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="medicamento",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medicamentos",
                to="inventario.proveedor",
            ),
        ),
        migrations.AddField(
            model_name="lotemedicamento",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes",
                to="inventario.proveedor",
            ),
        ),
        migrations.CreateModel(
            name="DireccionProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("calle", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=20)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ciudad", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direcciones",
                        to="inventario.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección de Proveedor",
                "verbose_name_plural": "Direcciones de Proveedores",
            },
        ),
        migrations.AddIndex(
            model_name="medicamento",
            index=models.Index(fields=["nombre"], name="inventario__nombre_bf6084_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="lotemedicamento",
            unique_together={("medicamento", "numero_lote")},
        ),
    ]
