# Generated by Django 5.0.6 on 2025-05-10 05:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotemedicamento",
            name="cantidad",
            field=models.PositiveIntegerField(
                validators=[core.validators.validar_cantidad_positiva]
            ),
        ),
        migrations.AlterField(
            model_name="lotemedicamento",
            name="fecha_vencimiento",
            field=models.DateField(validators=[core.validators.validar_fecha_futura]),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="precio_compra",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[core.validators.validar_precio_positivo],
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[core.validators.validar_precio_positivo],
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="stock_minimo",
            field=models.PositiveIntegerField(
                validators=[core.validators.validar_cantidad_positiva]
            ),
        ),
    ]
