# Generated by Django 5.0.6 on 2025-05-10 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mascotas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateTimeField()),
                ("motivo", models.TextField()),
                ("diagnostico", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PROGRAMADA",
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RUTINA", "Rutina"),
                            ("EMERGENCIA", "Emergencia"),
                            ("SEGUIMIENTO", "Seguimiento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duracion_estimada",
                    models.PositiveIntegerField(help_text="Duración en minutos"),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas_programadas",
                        to="mascotas.mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "indexes": [
                    models.Index(
                        fields=["mascota"], name="citas_consu_mascota_41299d_idx"
                    ),
                    models.Index(
                        fields=["veterinario"], name="citas_consu_veterin_4f611a_idx"
                    ),
                    models.Index(fields=["fecha"], name="citas_consu_fecha_77806b_idx"),
                    models.Index(
                        fields=["estado"], name="citas_consu_estado_1e4ec3_idx"
                    ),
                ],
            },
        ),
    ]
