# Generated by Django 5.0.6 on 2025-05-10 05:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="fecha",
            field=models.DateTimeField(
                validators=[core.validators.validar_fecha_futura]
            ),
        ),
    ]
