# Generated by Django 5.0.6 on 2025-05-14 16:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso en kilogramos",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="sintomas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="temperatura",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Temperatura en grados Celsius",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="tratamiento",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="duracion_estimada",
            field=models.PositiveIntegerField(
                help_text="Duración en minutos",
                validators=[core.validators.validar_cantidad_positiva],
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PROGRAMADA", "Programada"),
                    ("EN_CURSO", "En curso"),
                    ("COMPLETADA", "Completada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PROGRAMADA",
                max_length=20,
            ),
        ),
    ]
